import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="grid h-screen place-items-center">{children}</div>
      </body>
    </html>
  );
}
